# .github/dependabot.yml
version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      python-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "deps(pip)"
    open-pull-requests-limit: 3

  # Ruby dependencies for Jekyll
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ruby-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "deps(bundler)"
    open-pull-requests-limit: 3
